version: 0.2
env:
  variables:
    STAGE: staging
phases:
  install:
    commands:
    - npm install --silent --progress=false -g serverless@1.42.3 > /dev/null 2>&1
    #- npm install --silent --progress=false -g npm > /dev/null 2>&1
    - npm install --silent serverless-deployment-bucket --save-dev
  pre_build:
    commands:
    - echo Prebuild phase...
  build:
    commands:
    - echo Build started on `date`
    - (cd aws/vpc && serverless deploy --force -v --env=${STAGE})
  post_build:
    commands:
    - echo Build completed on `date`
